const fs=require('fs'),vm=require('vm'),assert=require('assert');
const source=fs.readFileSync('demo/custom_components/quack_material_demo/inventory.js','utf8');
const helpers=source.split('class QuackInventoryCard')[0].replace(/^export /gm,'');
const ctx={URL,crypto:require('crypto').webcrypto};vm.runInNewContext(helpers+';globalThis.decode=decodeSpool;globalThis.mg=gramsToMg;globalThis.esc=escapeHtml;',ctx);
vm.runInNewContext(helpers+';globalThis.profileLabel=materialProfileLabel;',ctx);
assert.equal(ctx.profileLabel({material_type:'PETG',material_preset:''}),'Standard PETG (resolved during Quack sync)');
assert.equal(ctx.profileLabel({material_type:'PLA',material_preset:'Elegoo special'}),'Elegoo special');
const insecure={URL,crypto:{getRandomValues:require('crypto').webcrypto.getRandomValues.bind(require('crypto').webcrypto)}};
vm.runInNewContext(helpers+';globalThis.requestId=newRequestId;',insecure);
const ids=new Set(Array.from({length:100},()=>insecure.requestId()));assert.equal(ids.size,100);for(const value of ids)assert.match(value,/^[0-9a-f]{8}-[0-9a-f]{4}-4[0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/);
const id='5b2d8b02-e906-4def-ba78-94465a775b66';
for(const payload of [id,'quackslicer://spool/'+id,'http://homeassistant.local:8123/dashboard-filament/rolls?spool='+id,'homeassistant://navigate/dashboard-filament/rolls?spool='+id])assert.equal(ctx.decode(payload),id);
assert.throws(()=>ctx.decode('homeassistant://call_service/dashboard-filament/rolls?spool='+id));
assert.throws(()=>ctx.decode('homeassistant://navigate/other?spool='+id));
assert.throws(()=>ctx.decode('http://example.com/?spool=invalid'));
assert.equal(ctx.mg('286,088'),286088);assert.throws(()=>ctx.mg('-2'));assert.throws(()=>ctx.mg('NaN'));
assert.equal(ctx.esc('<img onerror="x">'),'&lt;img onerror=&quot;x&quot;&gt;');console.log('URL/UUID, decimal input and HTML escaping pass');
const ui={HTMLElement:class{},customElements:{define(){}},window:{},URL,crypto:require('crypto').webcrypto,location:{href:'http://homeassistant.local:8123/dashboard-filament/slots'}};
vm.runInNewContext(source+';globalThis.Card=QuackInventoryCard;',ui);
const card=Object.create(ui.Card.prototype);card.view='slots';card.query='';card.message='';
card.data={can_edit:true,slots:[{id:'A1',spool_uuid:null},{id:'HT1',spool_uuid:null}],spools:[]};
card.shadowRoot={querySelectorAll(){return []},querySelector(sel){if(sel==='#scan')return {value:id};if(sel==='#slot')return {value:'HT1'};return {}}};
card.render();assert.ok(card.shadowRoot.innerHTML.includes('value="'+id+'"'));assert.ok(card.shadowRoot.innerHTML.includes('<option selected>HT1</option>'));
card.editor=(title,fields)=>{
  assert.match(fields,/<input name="material_preset"[^>]*>/);
  assert.doesNotMatch(fields.match(/<input name="material_preset"[^>]*>/)[0],/required/);
};
card.shadowRoot.querySelector=()=>({setAttribute(){}});
card.handle('new-roll','').then(()=>console.log('Optional special preset field and visible standard selection pass')).catch(err=>{console.error(err);process.exitCode=1;});
